#!/usr/bin/env bash

curl -X POST -H "Content-Type: application/json" -d '{"username": "Fortune", "password": "Fort", "email": "fortune@gmail.com"}' "http://0.0.0.0:5000/api/v1/user"
curl -X POST -H "Content-Type: application/json" -d '{"username": "Amie", "password": "Am", "email": "amie@gmail.com"}' "http://0.0.0.0:5000/api/v1/user"
curl -X GET "http://0.0.0.0:5000/api/v1/users/"
curl -X PUT -H "Content-Type: application/json" -d '{"email": "Edited"}' "http://0.0.0.0:5000/api/v1/user/1"
curl -X PUT -H "Content-Type: application/json" -d '{"pswd": "friend"}' "http://0.0.0.0:5000/api/v1/user/2"
curl -X GET "http://0.0.0.0:5000/api/v1/user/2"
curl -X DELETE "http://0.0.0.0:5000/api/v1/user/1"
curl -X GET "http://0.0.0.0:5000/api/v1/users/"

