#!/usr/bin/env bash

curl -X POST -H "Content-Type: application/json" -d '{"budg_id": 2, "total": 8, "desc": "Item2200"}' "http://0.0.0.0:5000/api/v1/budget_item"
curl -X POST -H "Content-Type: application/json" -d '{"budg_id": 2, "total": 8, "desc": "Item3300"}' "http://0.0.0.0:5000/api/v1/budget_item"
curl -X GET "http://0.0.0.0:5000/api/v1/budget_item/budget/7"
curl -X PUT -H "Content-Type: application/json" -d '{"desc": "Edited"}' "http://0.0.0.0:5000/api/v1/budget_item/1"
curl -X PUT -H "Content-Type: application/json" -d '{"desc": "Edited"}' "http://0.0.0.0:5000/api/v1/budget_item/2"
curl -X GET "http://0.0.0.0:5000/api/v1/budget_item/2"
curl -X DELETE "http://0.0.0.0:5000/api/v1/budget_item/1"
curl -X GET "http://0.0.0.0:5000/api/v1/budget_item/budget/7"
