#!/usr/bin/env bash

curl -X POST -H "Content-Type: application/json" -d '{"total": 4, "event_id": 2}' "http://0.0.0.0:5000/api/v1/budget"
curl -X GET "http://0.0.0.0:5000/api/v1/budget/event/2"
curl -X PUT -H "Content-Type: application/json" -d '{"total": 4000}' "http://0.0.0.0:5000/api/v1/budget/1"
curl -X PUT -H "Content-Type: application/json" -d '{"total": 2000}' "http://0.0.0.0:5000/api/v1/budget/2"
curl -X GET "http://0.0.0.0:5000/api/v1/budget/1"
curl -X DELETE "http://0.0.0.0:5000/api/v1/budget/1"
curl -X POST -H "Content-Type: application/json" -d '{"total": 6, "event_id": 2}' "http://0.0.0.0:5000/api/v1/budget"
curl -X GET "http://0.0.0.0:5000/api/v1/budget/event/2"
