#!/usr/bin/env bash

curl -X POST -H "Content-Type: application/json" -d '{"event_id": 2, "name": "Task100"}' "http://0.0.0.0:5000/api/v1/task"
curl -X POST -H "Content-Type: application/json" -d '{"event_id": 2, "name": "Task200"}' "http://0.0.0.0:5000/api/v1/task"
curl -X GET "http://0.0.0.0:5000/api/v1/task/event/3"
curl -X PUT -H "Content-Type: application/json" -d '{"desc": "Edited"}' "http://0.0.0.0:5000/api/v1/task/1"
curl -X PUT -H "Content-Type: application/json" -d '{"desc": "Edited"}' "http://0.0.0.0:5000/api/v1/task/2"
curl -X GET "http://0.0.0.0:5000/api/v1/task/2"
curl -X DELETE "http://0.0.0.0:5000/api/v1/task/2"
curl -X GET "http://0.0.0.0:5000/api/v1/task/event/3"

